version: "3"
services:
    mock_dsp:
        build: ./mock/
        restart: always
    
    ssp:
        build: ./ssp/
        restart: always
        ports:
            - 8888:8081
        environment:
            - DSPHOSTS=${HOST1} ${HOST2}