version: "3"
services:
    mock_dsp:
        build: ./mock/
        restart: always

    ssp:
        build: 
            context: ./ssp/
            args:
                PROJECTPATH: ${PWD}
        restart: always
        network_mode: host
        environment:
            - DSPHOSTS=${HOST1} ${HOST2}