version: "3"
services:
    mock_dsp:
        build: ./mock/ 
        restart: always

    ssp:
        build: ./ssp/
        restart: always
        network_mode: host
        environment:
            - DSPHOSTS=${HOST1} ${HOST2}
        volumes:
            - ./ssp/default.conf:/etc/nginx/conf.d/default.conf