version: "3.3"
services:
    mock_dsp:
        build: ./mock/
        restart: always
    # ssp:
    #     build: /.
    #     container_name: ssp
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     depends_on:
    #         - postgres
    #     environment:
    #         PORT:8080